trigger:
- main
 
pool:
  vmImage: 'windows-latest'
 
variables:
  buildConfiguration: 'Release'
 
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '4.8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
    includePreviewVersions: true
 
- task: NuGetToolInstaller@1
 
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path "$(Build.SourcesDirectory)\**\bin\$(buildConfiguration)\*" -Destination "$(build.artifactStagingDirectory)" -Recurse
 