trigger: none

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

stages:
- stage: build
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: build
    displayName: run build and test
    steps:
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '**\*.sln'

    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: '**\*.sln'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\WebDeploy" /p:AutoParameterizationWebConfigConnectionStrings=false'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
    - task: CopyFiles@2
      displayName: 'Copy Files DACPAC'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: 'FabrikamFiber.Database\bin\**\*.dacpac'
        TargetFolder: '$(build.artifactstagingdirectory)\DACPAC'
        OverWrite: true

    - task: CopyFiles@2
      displayName: 'Copy Files Selenium'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          FabrikamFiber.Web.PureSeleniumTests\bin\**\*
          **\*.testsettings
          **\*.runsettings
        TargetFolder: '$(build.artifactstagingdirectory)\Selenium'
        OverWrite: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact WebApp'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)\WebDeploy'
        ArtifactName: WebApp